# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub',
            field=models.CharField(default=1987, max_length=20),
            preserve_default=False,
        ),
    ]
