# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shift_choices',
            field=models.CharField(choices=[(b'dy', b'Day Shift'), (b'ng', b'Night Shift')], default=b'dy', max_length=2),
        ),
    ]
