# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_shift_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shift_choices',
            field=models.CharField(choices=[(b'D', b'Day Shift'), (b'N', b'Night Shift')], default=b'D', max_length=1),
        ),
    ]
