# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20190726_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=b'files/test.txt', upload_to=b''),
        ),
    ]
